---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Detect OS distribution and install Python 3.9 on Rocky Linux 8
      ansible.builtin.raw: |
        if [ -f /etc/os-release ]; then
          . /etc/os-release
          if [ "$ID" = "rocky" ] && [ "$VERSION_ID" = "8" ]; then
            if ! command -v python3.9 &> /dev/null; then
              dnf install -y python39 python39-pip
            fi
          fi
        fi
      register: prepare_result
      changed_when: "'python39' in prepare_result.stdout or 'already installed' in prepare_result.stdout"
      failed_when: false
      become: true
