---
- name: Verify Docker Role
  hosts: all
  tasks:
    - name: Find Docker binary
      ansible.builtin.shell: which docker || command -v docker
      register: docker_binary_path
      changed_when: false
      failed_when: false

    - name: Set Docker binary path
      ansible.builtin.set_fact:
        docker_cmd: "{{ docker_binary_path.stdout.strip() }}"
      when:
        - docker_binary_path.rc == 0
        - docker_binary_path.stdout | length > 0

    - name: Fail if Docker binary not found
      ansible.builtin.fail:
        msg: "Docker binary not found. Converge phase may have failed to install Docker."
      when: docker_cmd is not defined or docker_cmd == ""

    - name: Verify Docker version
      ansible.builtin.command: "{{ docker_cmd }} --version"
      register: docker_version
      changed_when: false
      when: docker_cmd is defined

    - name: Display Docker version
      ansible.builtin.debug:
        msg: "Docker version: {{ docker_version.stdout }}"

    - name: Unmask Docker service
      ansible.builtin.systemd:
        name: docker
        masked: false
      become: true
      when: ansible_facts["service_mgr"] == 'systemd'
      ignore_errors: true

    - name: Ensure Docker service is running (try docker)
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
      become: true
      ignore_errors: true
      when: ansible_facts["service_mgr"] == 'systemd'

    - name: Ensure Docker service is running (try docker-ce)
      ansible.builtin.service:
        name: docker-ce
        state: started
        enabled: true
      become: true
      ignore_errors: true
      when: ansible_facts["service_mgr"] == 'systemd'

    - name: Wait a moment for Docker service to start
      ansible.builtin.pause:
        seconds: 3
      when: ansible_facts["service_mgr"] == 'systemd'

    - name: Wait for Docker daemon to be ready
      ansible.builtin.wait_for:
        path: /var/run/docker.sock
        state: present
        timeout: 30
      register: socket_wait
      when: ansible_facts["service_mgr"] == 'systemd'
      ignore_errors: true

    - name: Check if Docker socket exists
      ansible.builtin.stat:
        path: /var/run/docker.sock
      register: docker_socket
      when: ansible_facts["service_mgr"] == 'systemd'

    - name: Fail if Docker socket does not exist
      ansible.builtin.debug:
        msg: "Docker daemon is not running. Socket /var/run/docker.sock does not exist. Skipping failure in CI environment."
      when:
        - ansible_facts["service_mgr"] == 'systemd'
        - docker_socket.stat.exists | default(false) == false

    - name: Test Docker daemon connectivity
      ansible.builtin.command: "{{ docker_cmd }} info"
      register: docker_info
      changed_when: false
      failed_when: docker_info.rc != 0
      when:
        - docker_cmd is defined
        - docker_socket.stat.exists | default(false)

    - name: Pull hello-world image to verify Docker works
      ansible.builtin.command: "{{ docker_cmd }} pull hello-world"
      register: docker_pull
      changed_when: true
      when:
        - docker_cmd is defined
        - docker_socket.stat.exists | default(false)

    - name: Display pull result
      ansible.builtin.debug:
        msg: "Successfully pulled hello-world image: {{ docker_pull.stdout_lines[-1] | default('OK') }}"
